services:
  db:
    image: mysql:8.0
    container_name: mysql_reto
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cecar
      MYSQL_DATABASE: reto_db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  web:
    build: ./app
    container_name: flask_reto
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge